version: "3.9"
services:
  pinger:
    build: .
    restart: unless-stopped
    container_name: "Pinger"
    network_mode: host
    volumes:
      - "${PWD}/out:/var/pinger"
    environment:
      CRON_MINUTES: "${CRON_MINUTES}"
