version: "3.9"
services:
  pinger:
    build: .
    restart: unless-stopped
    container_name: "Pinger"
    network_mode: host
    volumes:
      - "${PWD}/out/docker:/var/pinger"
    environment:
      CRON_MINUTES: "${CRON_MINUTES}"
  server:
    image: crazyuploader/markdown_server
    restart: unless-stopped
    container_name: "Markdown-Server"
    ports:
      - "${HOST:-127.0.0.1}:${PORT:-8080}:80"
      - "${HOST:-127.0.0.1}:${AUTO_RELOAD_PORT:-8081}:35729"
    volumes:
      - "${PWD}/out/docker:/markdown:ro"
