version: "3.9"
services:
  pinger:
    build:
      context: .
      args:
        TIME_ZONE: "${TIME_ZONE:-Asia/Kolkata}"
    restart: unless-stopped
    container_name: "Pinger"
    network_mode: host
    volumes:
      - "${PWD}/out:/var/pinger"
    environment:
      CRON_MINUTES: "${CRON_MINUTES}"
  server:
    image: crazyuploader/markdown_server
    restart: unless-stopped
    container_name: "Markdown-Server"
    ports:
      - "${HOST:-127.0.0.1}:${PORT:-8080}:80"
      - "${HOST:-127.0.0.1}:8081:35729"
    volumes:
      - "${PWD}/out:/markdown:ro"
