name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker Build
        run: docker build -t crazyuploader/pinger:latest .

      - name: Run ShellCheck
        run: shellcheck *.sh
