name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Docker Build
        run: docker build -t crazyuploader/pinger:latest .
        
      - name: Docker Compose Run
        run: |
          cp .env-example .env
          docker-compose up --detach

      - name: Run ShellCheck
        run: shellcheck *.sh
