name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Docker Build
        run: docker build -t crazyuploader/pinger:latest .
        
      - name: Docker Compose Run
        run: |
          cp .env-example .env
          docker-compose up --detach

      - name: Run ShellCheck
        run: shellcheck *.sh
